version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/l4proxy"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/cmd/l4proxy"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/cmd/service-announcer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
