version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
    - "/l4proxy"
    - "/cmd/l4proxy"
    - "/cmd/service-announcer"
    - "/"
    schedule:
      interval: "weekly"
    groups:
      go-deps:
        patterns:
        - '*'
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-deps:
        patterns:
        - '*'
