version: "2"
run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nolintlint
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    lll:
      line-length: 197
    goimports:
      local-prefixes: github.com/makkes/l4proxy

formatters:
  enable:
    - gofmt
    - goimports
