# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
  - id: lint-go-code
    name: Lint go code
    entry: make lint
    files: (^go\.(mod|sum)|\.go$)
    language: system
    stages: [commit]
    pass_filenames: false
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
    stages: [commit]
  - id: end-of-file-fixer
    stages: [commit]
  - id: check-yaml
    stages: [commit]
  - id: check-added-large-files
    stages: [commit]
  - id: mixed-line-ending
    args: ["-f", "lf"]
    exclude: \.bat$
    stages: [commit]
  - id: no-commit-to-branch
    stages: [commit]
  - id: check-added-large-files
    stages: [commit]
  - id: check-case-conflict
    stages: [commit]
  - id: check-merge-conflict
    stages: [commit]
  - id: forbid-new-submodules
    stages: [commit]
  - id: check-executables-have-shebangs
    stages: [commit]
  - id: check-symlinks
    stages: [commit]
  - id: end-of-file-fixer
    stages: [commit]
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.16.0
  hooks:
  - id: gitlint
    stages: [commit-msg]
